repository: Cyberiums/cyberium

theme: minima

keep_files:
  - static

favicon: /static/images/favicon.ico

defaults:
  - scope:
      path: ""
    values:
      layout: sidebar
  - scope:
      path: "*"
    values:
      root: "../.."
  - scope:
      path: "*/*"
    values:
      root: "../.."

default_root: "../.."

collections_dir: docs
collections:
  getting-started:
    output: true
    caption: Platform Introduction
    sidebar_index: 1
    frontpage: _getting-started/index.md
  signup-and-start:
    output: true
    permalink: docs/:collection/:slug
    caption: Cloud Startup
    sidebar_index: 2
    frontpage: _signup-and-start/signup-studio-account.md
  interface:
    output: true
    permalink: docs/:collection/:slug
    caption: Using SOLYD
    sidebar_index: 3
  dapp:
    output: true
    permalink: docs/:collection/:slug
    caption: For dApp Developers
    frontpage: _dapp/native.md
    sidebar_index: 4
  api:
    output: true
    permalink: docs/:collection/:slug
    caption: API & Hooks
    frontpage: _api/types.md
    sidebar_index: 5
  developers:
    output: true
    permalink: docs/:collection/:slug
    caption: Screen Design
    frontpage: _developers/devguide.md
    sidebar_index: 6
  clef:
    output: true
    permalink: docs/:collection/:slug
    caption: Scripts
    sidebar_index: 7
    frontpage: _clef/Tutorial.md
  whisper:
    output: true
    permalink: docs/:collection/:slug
    caption: Blockchain
    sidebar_index: 8
    frontpage: _whisper/Whisper-Overview.md

collections_dir: webinars
collections:
  getting-started:
    output: true
    caption: Webinars
    sidebar_index: 1
    frontpage: _api_security/index.md
